import type { Metadata } from "next";
import React from "react";
import Home from "./pages/Home/page";

function page() {
  return <Home />;
}

export const metadata: Metadata = {
  title: "Home",
  description: "Generated by create next app",
};

export default page;
